name: Unit tests

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: Install libEGL
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev libegl1 libglu1-mesa libgl1-mesa-dev xvfb libxcb-cursor0
      - name: Run tests
        run: pytest -s